# ─────────────────────────────────────────────
#  NSE Stock Universe  —  All Sectors
#  Yahoo Finance: add ".NS" suffix at fetch time
# ─────────────────────────────────────────────

NIFTY_50 = [
    "RELIANCE","TCS","HDFCBANK","BHARTIARTL","ICICIBANK",
    "INFY","SBIN","HINDUNILVR","ITC","LT","KOTAKBANK","BAJFINANCE",
    "HCLTECH","AXISBANK","WIPRO","ASIANPAINT","MARUTI","SUNPHARMA",
    "ULTRACEMCO","NTPC","POWERGRID","TITAN","BAJAJFINSV","NESTLEIND",
    "INDUSINDBK","TATAMOTORS","ONGC","JSWSTEEL","TECHM","COALINDIA",
    "HDFCLIFE","GRASIM","HINDALCO","DRREDDY","CIPLA","BPCL",
    "BRITANNIA","EICHERMOT","APOLLOHOSP","DIVISLAB","SBILIFE",
    "TATACONSUM","HEROMOTOCO","SHREECEM","M&M","BAJAJ-AUTO",
    "ADANIPORTS","TATASTEEL","ADANIENT","UPL",
]

NIFTY_NEXT_50 = [
    "PIDILITIND","SIEMENS","HAVELLS","MUTHOOTFIN","LUPIN",
    "TORNTPHARM","BERGEPAINT","COLPAL","DABUR","MARICO","AMBUJACEM",
    "ACC","INDIGO","TRENT","DMART","NYKAA","ZOMATO","PNB",
    "BANKBARODA","CANBK","IDFCFIRSTB","FEDERALBNK","MPHASIS",
    "PERSISTENT","LTIM","COFORGE","KPIT","TATAELXSI","DIXON","VOLTAS",
    "POLYCAB","SUPREMEIND","ASTRAL","PAGEIND","VARUNBEV","GODREJCP",
    "EMAMILTD","GLENMARK","ALKEM","BIOCON","AUROPHARMA","IPCALAB",
    "SAIL","NMDC","JINDALSTEL","RATNAMANI","APOLLOTYRE","MOTHERSON",
    "BALKRISIND","OFSS",
]

NIFTY_MIDCAP = [
    "MRF","EXIDEIND","CUMMINSIND","THERMAX","ABB","BHEL","BEL","HAL",
    "GRINDWELL","AIAENG","BOSCHLTD","FORCEMOT","TIINDIA","SOLARINDS",
    "PIIND","RADICO","SUZLON","CESC","TATAPOWER","TORNTPOWER",
    "PETRONET","GAIL","MGL","IGL","GUJGASLTD","CONCOR","IRCTC",
    "LALPATHLAB","METROPOLIS","FORTIS","MAXHEALTH","CHOLAFIN","LTTS",
    "CYIENT","ZENSAR","MCDOWELL-N","KPITTECH","INFOEDGE",
    "DEEPAKNTR","AAVAS","FINOLEXIND","KEI","CROMPTON","AMBER",
    "WHIRLPOOL","BLUESTAR","MINDA","ENDURANCE","ESCORTS","GREENPANEL",
    "CENTURYPLY","APLAPOLLO","JSWENERGY","ADANIGREEN","HINDPETRO",
    "CASTROLIND","AARTI","GODREJPROP","OBEROIRLTY","PHOENIXLTD",
    "PRESTIGE","SOBHA","BRIGADE","SUNTV","PVRINOX","SAREGAMA",
    "TATACHEM","FINEORG","AARTIIND","GALAXYSURF","CLEAN","HOMEFIRST",
    "APTUS","SUPRAJIT","TITAGARH","RAILTEL","RVNL","IRFC","PFC",
    "RECLTD","HUDCO","SJVN","NHPC","CDSL","BSE","MCX","ICICIGI",
    "HDFCAMC","NIPPONLIFE","UTIAMC","360ONE","IIFL","MANAPPURAM",
    "EDELWEISS","MOTILALOFS","NUVOCO","JKCEMENT","RAMCOCEM","DALMIA",
    "HEIDELBERG","BIRLACORP","VEDL","HINDZINC","MOIL","NATCO",
    "LAURUSLABS","GRANULES","IPCA","ERIS","JBCHEPHARM","PIRAMALENT",
    "CEATLTD","TVSMOTORS","SONACOMS","ATUL","FLAIR","NIACL",
]

# ── SECTOR INDICES ─────────────────────────────
NIFTY_BANK = [
    "HDFCBANK","ICICIBANK","KOTAKBANK","SBIN","AXISBANK",
    "INDUSINDBK","BANDHANBNK","IDFCFIRSTB","FEDERALBNK",
    "PNB","BANKBARODA","CANBK","UNIONBANK","INDIANB",
]

NIFTY_IT = [
    "TCS","INFY","HCLTECH","WIPRO","TECHM","LTIM","MPHASIS",
    "PERSISTENT","COFORGE","TATAELXSI","KPITTECH","CYIENT","ZENSAR",
    "LTTS","OFSS","NIITTECH",
]

NIFTY_PHARMA = [
    "SUNPHARMA","DRREDDY","CIPLA","DIVISLAB","BIOCON","AUROPHARMA",
    "LUPIN","TORNTPHARM","ALKEM","IPCALAB","GLENMARK","NATCO",
    "LAURUSLABS","GRANULES","IPCA","ERIS","JBCHEPHARM","PIRAMALENT",
    "ABBOTINDIA","PFIZER","SANOFI","GLAXO","JBMA","CAPLIPOINT",
    "LAXCHEMI","SEQUENT","SUVEN","SOLARA",
]

NIFTY_AUTO = [
    "MARUTI","TATAMOTORS","M&M","BAJAJ-AUTO","EICHERMOT","HEROMOTOCO",
    "TVSMOTORS","APOLLOTYRE","CEATLTD","BALKRISIND","MOTHERSON",
    "ENDURANCE","ESCORTS","MINDA","TIINDIA","SONACOMS","SWARAJENG",
    "SUPRAJIT","BOSCHLTD","FORCEMOT","ASHOKLEY","BHARATFORG",
]

NIFTY_FMCG = [
    "HINDUNILVR","ITC","NESTLEIND","BRITANNIA","DABUR","MARICO",
    "COLPAL","GODREJCP","EMAMILTD","TATACONSUM","VARUNBEV","MCDOWELL-N",
    "RADICO","PARAGMILK","BIKAJI","DEVYANI","SAPPHIRE","VBL",
]

NIFTY_METAL = [
    "TATASTEEL","JSWSTEEL","HINDALCO","SAIL","NMDC","JINDALSTEL",
    "VEDL","HINDZINC","MOIL","RATNAMANI","APLAPOLLO","WELCORP",
    "NATSTEELS","APL","SHYAMMETL",
]

NIFTY_ENERGY = [
    "RELIANCE","ONGC","BPCL","IOC","HINDPETRO","GAIL","PETRONET",
    "MGL","IGL","GUJGASLTD","TATAPOWER","NTPC","POWERGRID",
    "ADANIGREEN","JSWENERGY","CESC","TORNTPOWER","SJVN","NHPC","SUZLON",
]

NIFTY_REALTY = [
    "GODREJPROP","OBEROIRLTY","PHOENIXLTD","PRESTIGE","SOBHA",
    "BRIGADE","DLF","LODHA","SUNTECK","KOLTEPATIL","MAHLIFE",
    "NUVOCO","INDIABULL","IBREALEST",
]

NIFTY_PSU_BANK = [
    "SBIN","PNB","BANKBARODA","CANBK","UNIONBANK","INDIANB",
    "CENTRALBK","MAHABANK","UCOBANK","IOB","BANDHANBNK",
]

NIFTY_INFRA = [
    "LT","ADANIPORTS","CONCOR","IRCTC","RVNL","RAILTEL","TITAGARH",
    "IRFC","PFC","RECLTD","HUDCO","BHEL","BEL","HAL",
    "SIEMENS","ABB","THERMAX","CUMMINSIND","GRINDWELL",
]

NIFTY_FINANCIAL = [
    "BAJFINANCE","BAJAJFINSV","HDFCLIFE","SBILIFE","ICICIGI","HDFCAMC",
    "NIPPONLIFE","UTIAMC","360ONE","MUTHOOTFIN","MANAPPURAM","CHOLAFIN",
    "IIFL","MOTILALOFS","ANGEL","CDSL","BSE","MCX","EDELWEISS",
    "IDFCFIRSTB","AAVAS","HOMEFIRST","APTUS","FEDERALBNK",
]

# ── ALL STOCKS combined (deduplicated) ──────────
import itertools
_all = list(dict.fromkeys(itertools.chain(
    NIFTY_50, NIFTY_NEXT_50, NIFTY_MIDCAP,
    NIFTY_BANK, NIFTY_IT, NIFTY_PHARMA, NIFTY_AUTO,
    NIFTY_FMCG, NIFTY_METAL, NIFTY_ENERGY, NIFTY_REALTY,
    NIFTY_PSU_BANK, NIFTY_INFRA, NIFTY_FINANCIAL,
)))
ALL_NSE = _all

# ── UNIVERSE MENU ───────────────────────────────
UNIVERSES = {
    "🏆 Nifty 50         (~50 stocks  1 min)"  : NIFTY_50,
    "📊 Nifty 100        (~100 stocks 2 min)"  : list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50)),
    "📈 Nifty 200        (~200 stocks 4 min)"  : list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP)),
    "🌐 All NSE Listed   (~300 stocks 6 min)"  : ALL_NSE,
    "──── SECTORS ────────────────────────────": [],
    "🏦 Nifty Bank       (14 stocks)"          : NIFTY_BANK,
    "💻 Nifty IT         (16 stocks)"          : NIFTY_IT,
    "💊 Nifty Pharma     (28 stocks)"          : NIFTY_PHARMA,
    "🚗 Nifty Auto       (22 stocks)"          : NIFTY_AUTO,
    "🛒 Nifty FMCG       (18 stocks)"          : NIFTY_FMCG,
    "🔩 Nifty Metal      (15 stocks)"          : NIFTY_METAL,
    "⚡ Nifty Energy      (20 stocks)"         : NIFTY_ENERGY,
    "🏠 Nifty Realty     (14 stocks)"          : NIFTY_REALTY,
    "🏛️ Nifty PSU Bank   (11 stocks)"         : NIFTY_PSU_BANK,
    "🏗️ Nifty Infra      (19 stocks)"         : NIFTY_INFRA,
    "💰 Nifty Financial  (24 stocks)"          : NIFTY_FINANCIAL,
}
